### ISSUE TITLE
Device fingerprinting IP Address?

### ISSUE THREAD

**Issue by chadsowald** [MicrosoftDocs/dynamics-365-fraud-protection#10]
Do merchants need to pass in the customer's IP address to device fingerprinting?  e.g. in the bullet list that says "When you submit transactions in the Dynamics 365 Fraud Protection API, complete the following actions:" do we need an additional bullet that says "Set the 'device.ipAddress' field to the customer's IP address that your website receives when they use your site.".  I'm not sure if this is needed or not, but our sample application does it.  Can we please check on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbdc54ff-7213-6919-853f-f6bcaa49df8f
* Version Independent ID: 61c52010-49db-df09-e038-23e5d01a5247
* Content: [Implement device fingerprinting - Dynamics 365 Fraud Protection](https://docs.microsoft.com/en-us/dynamics365/fraud-protection/device-fingerprinting)
* Content Source: [content/device-fingerprinting.md](https://github.com/MicrosoftDocs/dynamics-365-fraud-protection/blob/master/content/device-fingerprinting.md)
* Service: **fraud-protection**
* GitHub Login: @YvonneDeQ
* Microsoft Alias: **v-madeq**

**Comment by YvonneDeQ** [comment]
This has been fixed in the October release version.

**Comment by YvonneDeQ** [comment]
https://review.docs.microsoft.com/en-us/dynamics365/fraud-protection/device-fingerprinting?branch=master
