### ISSUE TITLE
Incorrect link to Loss Prevention Schemas

### ISSUE THREAD

**Issue by chadsowald** [MicrosoftDocs/dynamics-365-fraud-protection#12]
Hi.  The text that says "required schemas" on this page is incorrectly linked AFAICT.  Please change the link to point to this page instead: https://docs.microsoft.com/en-us/dynamics365/fraud-protection/view-loss-prevent-schemas

Thank you. ~Chad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55d2c797-86eb-9dd0-29cd-2c7f2fe2917f
* Version Independent ID: d814625e-09fa-2eef-3038-6bec5c7e6a5e
* Content: [Upload historical data for loss prevention - Dynamics 365 Fraud Protection](https://docs.microsoft.com/en-us/dynamics365/fraud-protection/loss-prevention-data-upload)
* Content Source: [content/loss-prevention-data-upload.md](https://github.com/MicrosoftDocs/dynamics-365-fraud-protection/blob/master/content/loss-prevention-data-upload.md)
* Service: **fraud-protection**
* GitHub Login: @YvonneDeQ
* Microsoft Alias: **v-madeq**

**Comment by YvonneDeQ** [comment]
Checked that the "required schemas" link in **Upload historical data for loss prevention (content/loss-prevention-data-upload.md)**  points to **Data schemas for loss prevention (https://docs.microsoft.com/en-us/dynamics365/fraud-protection/view-loss-prevent-schemas)**.
It looks like the link does point to this page  - let me know if I am missing something.
Thank you, Yvonne

**Comment by chadsowald** [comment]
Yep, thanks @YvonneDeQ!  It got fixed with the December doc changes thankfully!  Have a nice weekend.
