### ISSUE TITLE
Does DFP work with GCC tenants?

### ISSUE THREAD

**Issue by grkoop** [MicrosoftDocs/dynamics-365-fraud-protection#14]
[Enter feedback here]
Any restrictions using this with GCC environments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f57f2f1-57c1-c9ee-3786-88f81c7b30d2
* Version Independent ID: 2a74ad26-0806-fd08-9d04-ff65117901ac
* Content: [Overview of Dynamics 365 Fraud Protection features - Dynamics 365 Fraud Protection](https://docs.microsoft.com/en-us/dynamics365/fraud-protection/overview)
* Content Source: [content/overview.md](https://github.com/MicrosoftDocs/dynamics-365-fraud-protection/blob/main/content/overview.md)
* Service: **dynamics-365-fraud-protection**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thank you for your comment. @kha-microsoft can you please take a look?

**Comment by kha-microsoft** [comment]
Hi @grkoop - unfortunately Fraud Protection can only be used with Commercial type Azure tenants. 
It cannot be used with GCC or B2C tenants.
