### ISSUE TITLE
Server2ServerAPI should be Risk_API

### ISSUE THREAD

**Issue by satyamamit** [MicrosoftDocs/dynamics-365-fraud-protection#2]
Server2ServerAPI should be renamed in doc as Risk_API as we dont have any role with name as Server2ServerAPI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3803181-7754-70ef-aec1-db596a85628e
* Version Independent ID: 3f0bee76-d82b-a15f-7ef0-c1072a98cdad
* Content: [Configure user access to Dynamics 365 Fraud Protection - Dynamics 365 Fraud Protection](https://docs.microsoft.com/en-us/dynamics365/fraud-protection/configure-user-access?source=docs#feedback)
* Content Source: [content/configure-user-access.md](https://github.com/MicrosoftDocs/dynamics-365-fraud-protection/blob/master/content/configure-user-access.md)
* Service: **fraud-protection**
* GitHub Login: @v-davido
* Microsoft Alias: **v-davido**

**Comment by josaw1** [comment]
Thank you for your feedback. @danholtMS can you please evaluate?
