### ISSUE TITLE
Bullet list near top isn't formatted nicely.

### ISSUE THREAD

**Issue by chadsowald** [MicrosoftDocs/dynamics-365-fraud-protection#3]
The bullet points starting with "Device attributes such a" all appear on one line.  I imagine you meant to have each bullet point on its own line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbdc54ff-7213-6919-853f-f6bcaa49df8f
* Version Independent ID: 61c52010-49db-df09-e038-23e5d01a5247
* Content: [Implement device fingerprinting - Dynamics 365 Fraud Protection](https://docs.microsoft.com/en-us/dynamics365/fraud-protection/device-fingerprinting#feedback)
* Content Source: [content/device-fingerprinting.md](https://github.com/MicrosoftDocs/dynamics-365-fraud-protection/blob/master/content/device-fingerprinting.md)
* Service: **fraud-protection**
* GitHub Login: @v-davido
* Microsoft Alias: **v-davido**

**Comment by josaw1** [comment]
Thank you for your feedback. I've fixed the bulleted list. Good catch!
