### ISSUE TITLE
Example challenge rule does not compile

### ISSUE THREAD

**Issue by chadsowald** [MicrosoftDocs/dynamics-365-fraud-protection#5]
This rule

```
Return Challenge(type = "sms", reason = "bot score") 
WHEN @botScore &lt; 900 AND @botScore &gt; 400 
````

Does not compile in the application.  It complains that "type" is not allowed in method "Challenge".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ccda595-6dac-c8e8-f2e9-a36a1b0a1676
* Version Independent ID: 1c82fe1e-7b1e-d5e8-816a-5142ad38e386
* Content: [Manage account protection rules and lists - Dynamics 365 Fraud Protection](https://docs.microsoft.com/en-us/dynamics365/fraud-protection/ap-rulesandlists)
* Content Source: [content/ap-rulesandlists.md](https://github.com/MicrosoftDocs/dynamics-365-fraud-protection/blob/master/content/ap-rulesandlists.md)
* Service: **fraud-protection**
* GitHub Login: @zhuoche
* Microsoft Alias: **v-davido**

**Comment by josaw1** [comment]
Hi. Thank you for your feedback. We've fixed the topic, please take a look.
