### ISSUE TITLE
Device fingerprinting error

### ISSUE THREAD

**Issue by chadsowald** [MicrosoftDocs/dynamics-365-fraud-protection#8]
Please remove the following line from the page:

"In the deviceContextDC field on the deviceContext object, set the window.dfp.dc variable from mdt.js response."

It no longer applies and isn't needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbdc54ff-7213-6919-853f-f6bcaa49df8f
* Version Independent ID: 61c52010-49db-df09-e038-23e5d01a5247
* Content: [Implement device fingerprinting - Dynamics 365 Fraud Protection](https://docs.microsoft.com/en-us/dynamics365/fraud-protection/device-fingerprinting)
* Content Source: [content/device-fingerprinting.md](https://github.com/MicrosoftDocs/dynamics-365-fraud-protection/blob/master/content/device-fingerprinting.md)
* Service: **fraud-protection**
* GitHub Login: @YvonneDeQ
* Microsoft Alias: **v-madeq**

**Comment by YvonneDeQ** [comment]
This has been fixed in the October release version.

**Comment by YvonneDeQ** [comment]
https://review.docs.microsoft.com/en-us/dynamics365/fraud-protection/device-fingerprinting?branch=master
