### ISSUE TITLE
Device fingerprinting verification

### ISSUE THREAD

**Issue by chadsowald** [MicrosoftDocs/dynamics-365-fraud-protection#9]
It could be good to mention how to verify device fingerprinting is setup correctly. I would suggest the following:

I would add a 3rd heading to the page "Verify device fingerprinting" with the following steps:
1. Send a transaction/signup/signin/etc to the Dynamics 365 Fraud Protection API, including the device fingerprinting deviceContextID.
1. Visit the Dynamics 365 Fraud Protection Portal (should include a link probably).
1. Go to the Graph Explorer (should include the nav path to this page)
1. Search for the transaction/signup/signin that you submitted.
1. You should see a "DeviceContext" node in graph.  Select it.
1. Verify that in the right panel you see additional details about your device (e.g. UserAgent, operating system version, etc...).  So long as you see additional details beyond what you submitted in the API call, you have correctly setup device fingerprinting.f

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbdc54ff-7213-6919-853f-f6bcaa49df8f
* Version Independent ID: 61c52010-49db-df09-e038-23e5d01a5247
* Content: [Implement device fingerprinting - Dynamics 365 Fraud Protection](https://docs.microsoft.com/en-us/dynamics365/fraud-protection/device-fingerprinting)
* Content Source: [content/device-fingerprinting.md](https://github.com/MicrosoftDocs/dynamics-365-fraud-protection/blob/master/content/device-fingerprinting.md)
* Service: **fraud-protection**
* GitHub Login: @YvonneDeQ
* Microsoft Alias: **v-madeq**

**Comment by Sirlupinwatson1** [comment]
Any Follow-up on this would be appreciated! --> Anyone have tested this solution? 

Thank you!

Regards, Armand B.

**Comment by josaw1** [comment]
Thanks for your feedback. @YvonneDeQ can you please take a look?

**Comment by Sirlupinwatson1** [comment]
Hi @josaw1 

I hope you are doing good and thank you for your messages, I appreciate it. 

If @chadsowald would be able to simply edit the proposed solution including the full path link and we can just review the solution and onboard it because it would fit in the Docs fingerprint. The full article itself is not yet completed or is still missing many details to me.

**Comment by YvonneDeQ** [comment]
Fix is being reviewed by PM.

**Comment by YvonneDeQ** [comment]
Changes as suggested completed and approved by the PM. 

•	[View changes in Implement device fingerprinting topic](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Freview.docs.microsoft.com%2Fen-us%2Fdynamics365%2Ffraud-protection%2Fdevice-fingerprinting%3Fbranch%3DOct-1-Rls&data=02%7C01%7Cv-madeq%40microsoft.com%7C7465c688a1844cf9a04a08d85f7d625d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637364339406392644&sdata=sqUP6QEboN1eLVldYBuSgKH7FFRmZhL2JQU260aZdT8%3D&reserved=0).

•	[View changes in GitHub](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdynamics-365-fraud-protection-pr%2Fcommit%2Febaaf66efb671587ed47aa312e818ee9c6b3789c%23diff-667e16d2af0545ca2a64cc0ce6feaddc&data=02%7C01%7Cv-madeq%40microsoft.com%7C7465c688a1844cf9a04a08d85f7d625d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637364339406402639&sdata=42tV1zpEei4I3h1se02rxoMgJKCX%2F9hberGiKIAxQzw%3D&reserved=0).

**Comment by Sirlupinwatson1** [comment]
Hi @YvonneDeQ 

Great work and thank you very much!

I wish you a great evening! 

Best Regards, Armand Brunelle

**Comment by chadsowald** [comment]
Thanks so much everyone.  Looks great. Feel free to close the issue if you no longer need it open to track anything.
